FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App
EXPOSE 8080

# Copy everything
COPY ./api ./api
COPY ./db-context ./db-context
COPY ./financial-data-provider ./financial-data-provider
COPY ./app-core ./app-core

WORKDIR /App/api
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release -o ./out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App/api
COPY --from=build-env /App/api/out .
ENTRYPOINT ["dotnet", "api.dll"]