version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - DBCONTEXT_DATABASE_URL=User ID=fincharts_user;Password=fincharts_pass;Host=db;Port=5432;Database=fincharts_db;
      - FINTACHARTS_API_URL=https://platform.fintacharts.com
      - FINTACHARTS_USERNAME=r_test@fintatech.com
      - FINTACHARTS_PASSWORD=kisfiz-vUnvy9-sopnyv
    depends_on:
      assets-fetcher:
        condition: service_completed_successfully
    networks:
      - default
    ports:
      - "8080:8080"
    restart: always
  assets-fetcher:
    build:
      context: .
      dockerfile: Dockerfile.assets-fetcher
    environment:
      - >
        DBCONTEXT_DATABASE_URL=User ID=fincharts_user;Password=fincharts_pass;Host=db;Port=5432;Database=fincharts_db;
      - FINTACHARTS_API_URL=https://platform.fintacharts.com
      - FINTACHARTS_USERNAME=r_test@fintatech.com
      - FINTACHARTS_PASSWORD=kisfiz-vUnvy9-sopnyv
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    environment:
      - POSTGRES_USER=fincharts_user
      - POSTGRES_PASSWORD=fincharts_pass
      - POSTGRES_DB=fincharts_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U fincharts_user -d fincharts_db'"]
      interval: 1s
      timeout: 1s
      retries: 10
volumes:
  db-data:
    driver: local
networks:
  default:
    driver: bridge
